apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test3-jxxa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test3-jxxa
    app.kubernetes.io/part-of: my-test3-2
  name: my-test3-jxxa0mdf
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: my-test3-jxxa
    weight: 100
status: {}
