apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test3-jxxa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test3-jxxa
    app.kubernetes.io/part-of: my-test3-2
  name: my-test3-jxxa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-test3-jxxa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-test3-jxxa
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mkosiarc-tenant/my-test3-2/my-test3-jxxa@sha256:da21608e25bd33d69060628381f113175202402b25b5269d90583312a7e53bdd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
